"""Plugin lifecycle — discovery, manifest parsing, Docker sandbox, approval.

Python port of ``rust/crates/corlinman-plugins``. Public surface mirrors the
Rust ``lib.rs`` re-exports 1:1 so call sites translate by name:

  * Discovery   : :class:`SearchRoot`, :class:`Origin`, :class:`DiscoveredPlugin`,
                  :class:`DiscoveryDiagnostic`, :func:`discover`,
                  :func:`roots_from_env_var`
  * Manifest    : :class:`PluginManifest`, :class:`PluginType`,
                  :class:`EntryPoint`, :class:`Capabilities`, :class:`Tool`,
                  :class:`SandboxConfig`, :class:`McpConfig`,
                  :class:`Communication`, :class:`RestartPolicy`,
                  :class:`AllowlistMode`, :class:`ToolsAllowlist`,
                  :class:`ResourcesAllowlist`, :class:`EnvPassthrough`,
                  :class:`ManifestParseError`, :func:`parse_manifest_file`
  * Registry    : :class:`PluginRegistry`, :class:`PluginEntry`,
                  :class:`Diagnostic`, :class:`ParseErrorDiagnostic`,
                  :class:`NameCollisionDiagnostic`
  * Async tasks : :class:`AsyncTaskRegistry`, :class:`CompleteError`,
                  :class:`AsyncTaskCompletionError`
  * Approval    : :class:`ApprovalQueue`, :class:`ApprovalStore`,
                  :class:`ApprovalRequest`, :class:`ApprovalRecord`,
                  :class:`ApprovalDecision`
  * Sandbox     : :class:`DockerRunner`, :class:`DockerSandbox`,
                  :class:`PluginOutput`, :func:`host_config_from`,
                  :func:`is_enabled`, :func:`parse_bytes`,
                  :class:`SandboxError` (+ subclasses)
  * Lifecycle   : :class:`PluginSupervisor`, :class:`PluginChild`,
                  :class:`PluginSupervisorError`,
                  :data:`PLUGIN_ADDR_ENV`
"""

from __future__ import annotations

from corlinman_providers.plugins.approval import (
    ApprovalDecision,
    ApprovalQueue,
    ApprovalRecord,
    ApprovalRequest,
    ApprovalStore,
)
from corlinman_providers.plugins.async_task import (
    AsyncTaskCompletionError,
    AsyncTaskRegistry,
    CompleteError,
)
from corlinman_providers.plugins.discovery import (
    DiscoveredPlugin,
    DiscoveryDiagnostic,
    DiscoveryResult,
    Origin,
    SearchRoot,
    discover,
    roots_from_env_var,
)
from corlinman_providers.plugins.lifecycle import (
    BACKOFF_SCHEDULE_SECONDS,
    CRASH_LOOP_WINDOW_SECONDS,
    MAX_RESTARTS_IN_WINDOW,
    PLUGIN_ADDR_ENV,
    PluginChild,
    PluginSupervisor,
    PluginSupervisorError,
    ServiceRuntimeProtocol,
)
from corlinman_providers.plugins.manifest import (
    KNOWN_HOOK_EVENTS,
    KNOWN_PROTOCOLS,
    MANIFEST_FILENAME,
    MAX_SUPPORTED_MANIFEST_VERSION,
    MCP_MIN_MANIFEST_VERSION,
    AllowlistMode,
    Capabilities,
    Communication,
    EntryPoint,
    EnvPassthrough,
    ManifestIoError,
    ManifestParseError,
    ManifestTomlError,
    ManifestValidationError,
    McpConfig,
    Meta,
    PluginManifest,
    PluginType,
    ResourcesAllowlist,
    RestartPolicy,
    SandboxConfig,
    Tool,
    ToolsAllowlist,
    parse_manifest_file,
)
from corlinman_providers.plugins.registry import (
    Diagnostic,
    NameCollisionDiagnostic,
    ParseErrorDiagnostic,
    PluginEntry,
    PluginRegistry,
)
from corlinman_providers.plugins.sandbox import (
    DEFAULT_SANDBOX_IMAGE,
    OOM_ERROR_CODE,
    DockerRunner,
    DockerSandbox,
    PluginOutput,
    SandboxCancelledError,
    SandboxConfigError,
    SandboxError,
    SandboxRuntimeError,
    SandboxTimeoutError,
    default_runner,
    host_config_from,
    is_enabled,
    parse_bytes,
    parse_response_line,
)

__all__ = [
    "BACKOFF_SCHEDULE_SECONDS",
    "CRASH_LOOP_WINDOW_SECONDS",
    "DEFAULT_SANDBOX_IMAGE",
    "KNOWN_HOOK_EVENTS",
    "KNOWN_PROTOCOLS",
    "MANIFEST_FILENAME",
    "MAX_RESTARTS_IN_WINDOW",
    "MAX_SUPPORTED_MANIFEST_VERSION",
    "MCP_MIN_MANIFEST_VERSION",
    "OOM_ERROR_CODE",
    "PLUGIN_ADDR_ENV",
    "AllowlistMode",
    "ApprovalDecision",
    "ApprovalQueue",
    "ApprovalRecord",
    "ApprovalRequest",
    "ApprovalStore",
    "AsyncTaskCompletionError",
    "AsyncTaskRegistry",
    "Capabilities",
    "Communication",
    "CompleteError",
    "Diagnostic",
    "DiscoveredPlugin",
    "DiscoveryDiagnostic",
    "DiscoveryResult",
    "DockerRunner",
    "DockerSandbox",
    "EntryPoint",
    "EnvPassthrough",
    "ManifestIoError",
    "ManifestParseError",
    "ManifestTomlError",
    "ManifestValidationError",
    "McpConfig",
    "Meta",
    "NameCollisionDiagnostic",
    "Origin",
    "ParseErrorDiagnostic",
    "PluginChild",
    "PluginEntry",
    "PluginManifest",
    "PluginOutput",
    "PluginRegistry",
    "PluginSupervisor",
    "PluginSupervisorError",
    "PluginType",
    "ResourcesAllowlist",
    "RestartPolicy",
    "SandboxCancelledError",
    "SandboxConfig",
    "SandboxConfigError",
    "SandboxError",
    "SandboxRuntimeError",
    "SandboxTimeoutError",
    "SearchRoot",
    "ServiceRuntimeProtocol",
    "Tool",
    "ToolsAllowlist",
    "default_runner",
    "discover",
    "host_config_from",
    "is_enabled",
    "parse_bytes",
    "parse_manifest_file",
    "parse_response_line",
    "roots_from_env_var",
]
