# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from corlinman_grpc._generated.corlinman.v1 import (
    agent_pb2 as corlinman_dot_v1_dot_agent__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in corlinman/v1/agent_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
            "/corlinman.v1.Agent/Chat",
            request_serializer=corlinman_dot_v1_dot_agent__pb2.ClientFrame.SerializeToString,
            response_deserializer=corlinman_dot_v1_dot_agent__pb2.ServerFrame.FromString,
            _registered_method=True,
        )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Chat": grpc.stream_stream_rpc_method_handler(
            servicer.Chat,
            request_deserializer=corlinman_dot_v1_dot_agent__pb2.ClientFrame.FromString,
            response_serializer=corlinman_dot_v1_dot_agent__pb2.ServerFrame.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "corlinman.v1.Agent", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("corlinman.v1.Agent", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/corlinman.v1.Agent/Chat",
            corlinman_dot_v1_dot_agent__pb2.ClientFrame.SerializeToString,
            corlinman_dot_v1_dot_agent__pb2.ServerFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
