# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corlinman/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "corlinman/v1/common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x63orlinman/v1/common.proto\x12\x0c\x63orlinman.v1"v\n\x07Message\x12 \n\x04role\x18\x01 \x01(\x0e\x32\x12.corlinman.v1.Role\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0ctool_call_id\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_json\x18\x05 \x01(\x0c"\x80\x01\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\r\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\r\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\r\x12\x15\n\rcached_tokens\x18\x04 \x01(\r\x12\x18\n\x10reasoning_tokens\x18\x05 \x01(\r"K\n\x0cTraceContext\x12\x13\n\x0btraceparent\x18\x01 \x01(\t\x12\x12\n\ntracestate\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t"t\n\tErrorInfo\x12,\n\x06reason\x18\x01 \x01(\x0e\x32\x1c.corlinman.v1.FailoverReason\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tretryable\x18\x03 \x01(\x08\x12\x15\n\rupstream_code\x18\x04 \x01(\t"g\n\x0e\x43hannelBinding\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x0e\n\x06thread\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x13\n\x0bsession_key\x18\x05 \x01(\t*K\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02\x12\n\n\x06SYSTEM\x10\x03\x12\x08\n\x04TOOL\x10\x04*\xcd\x01\n\x0e\x46\x61iloverReason\x12\x1f\n\x1b\x46\x41ILOVER_REASON_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x42ILLING\x10\x01\x12\x0e\n\nRATE_LIMIT\x10\x02\x12\x08\n\x04\x41UTH\x10\x03\x12\x12\n\x0e\x41UTH_PERMANENT\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05\x12\x13\n\x0fMODEL_NOT_FOUND\x10\x06\x12\n\n\x06\x46ORMAT\x10\x07\x12\x14\n\x10\x43ONTEXT_OVERFLOW\x10\x08\x12\x0e\n\nOVERLOADED\x10\t\x12\x0b\n\x07UNKNOWN\x10\nB\x02H\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "corlinman.v1.common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\001"
    _globals["_ROLE"]._serialized_start = 594
    _globals["_ROLE"]._serialized_end = 669
    _globals["_FAILOVERREASON"]._serialized_start = 672
    _globals["_FAILOVERREASON"]._serialized_end = 877
    _globals["_MESSAGE"]._serialized_start = 43
    _globals["_MESSAGE"]._serialized_end = 161
    _globals["_USAGE"]._serialized_start = 164
    _globals["_USAGE"]._serialized_end = 292
    _globals["_TRACECONTEXT"]._serialized_start = 294
    _globals["_TRACECONTEXT"]._serialized_end = 369
    _globals["_ERRORINFO"]._serialized_start = 371
    _globals["_ERRORINFO"]._serialized_end = 487
    _globals["_CHANNELBINDING"]._serialized_start = 489
    _globals["_CHANNELBINDING"]._serialized_end = 592
# @@protoc_insertion_point(module_scope)
