# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from corlinman_grpc._generated.corlinman.v1 import (
    embedding_pb2 as corlinman_dot_v1_dot_embedding__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in corlinman/v1/embedding_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EmbeddingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
            "/corlinman.v1.Embedding/Embed",
            request_serializer=corlinman_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            response_deserializer=corlinman_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            _registered_method=True,
        )
        self.EmbedBatch = channel.stream_stream(
            "/corlinman.v1.Embedding/EmbedBatch",
            request_serializer=corlinman_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            response_deserializer=corlinman_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            _registered_method=True,
        )


class EmbeddingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EmbedBatch(self, request_iterator, context):
        """EmbedBatch: client-streaming + server-streaming for large ingest pipelines.
        Order is preserved by `request_id`; batches may be flushed independently.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EmbeddingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Embed": grpc.unary_unary_rpc_method_handler(
            servicer.Embed,
            request_deserializer=corlinman_dot_v1_dot_embedding__pb2.EmbedRequest.FromString,
            response_serializer=corlinman_dot_v1_dot_embedding__pb2.EmbedResponse.SerializeToString,
        ),
        "EmbedBatch": grpc.stream_stream_rpc_method_handler(
            servicer.EmbedBatch,
            request_deserializer=corlinman_dot_v1_dot_embedding__pb2.EmbedRequest.FromString,
            response_serializer=corlinman_dot_v1_dot_embedding__pb2.EmbedResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "corlinman.v1.Embedding", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("corlinman.v1.Embedding", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Embedding(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/corlinman.v1.Embedding/Embed",
            corlinman_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            corlinman_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EmbedBatch(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/corlinman.v1.Embedding/EmbedBatch",
            corlinman_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            corlinman_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
