# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corlinman/v1/embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "corlinman/v1/embedding.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from corlinman_grpc._generated.corlinman.v1 import (
    common_pb2 as corlinman_dot_v1_dot_common__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1c\x63orlinman/v1/embedding.proto\x12\x0c\x63orlinman.v1\x1a\x19\x63orlinman/v1/common.proto"z\n\x0c\x45mbedRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05texts\x18\x02 \x03(\t\x12\r\n\x05route\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12)\n\x05trace\x18\x05 \x01(\x0b\x32\x1a.corlinman.v1.TraceContext"\x97\x01\n\rEmbedResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12.\n\x07vectors\x18\x02 \x03(\x0b\x32\x1d.corlinman.v1.EmbeddingVector\x12\x0b\n\x03\x64im\x18\x03 \x01(\r\x12\r\n\x05model\x18\x04 \x01(\t\x12&\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x17.corlinman.v1.ErrorInfo"\x1f\n\x0f\x45mbeddingVector\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x98\x01\n\tEmbedding\x12@\n\x05\x45mbed\x12\x1a.corlinman.v1.EmbedRequest\x1a\x1b.corlinman.v1.EmbedResponse\x12I\n\nEmbedBatch\x12\x1a.corlinman.v1.EmbedRequest\x1a\x1b.corlinman.v1.EmbedResponse(\x01\x30\x01\x42\x02H\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "corlinman.v1.embedding_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\001"
    _globals["_EMBEDREQUEST"]._serialized_start = 73
    _globals["_EMBEDREQUEST"]._serialized_end = 195
    _globals["_EMBEDRESPONSE"]._serialized_start = 198
    _globals["_EMBEDRESPONSE"]._serialized_end = 349
    _globals["_EMBEDDINGVECTOR"]._serialized_start = 351
    _globals["_EMBEDDINGVECTOR"]._serialized_end = 382
    _globals["_EMBEDDING"]._serialized_start = 385
    _globals["_EMBEDDING"]._serialized_end = 537
# @@protoc_insertion_point(module_scope)
