# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corlinman/v1/llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "corlinman/v1/llm.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from corlinman_grpc._generated.corlinman.v1 import (
    common_pb2 as corlinman_dot_v1_dot_common__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x63orlinman/v1/llm.proto\x12\x0c\x63orlinman.v1\x1a\x19\x63orlinman/v1/common.proto"\xf8\x01\n\x0b\x43hatRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\'\n\x08messages\x18\x02 \x03(\x0b\x32\x15.corlinman.v1.Message\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nmax_tokens\x18\x04 \x01(\r\x12\r\n\x05top_p\x18\x05 \x01(\x02\x12\x0c\n\x04stop\x18\x06 \x03(\t\x12\x0e\n\x06stream\x18\x07 \x01(\x08\x12\x12\n\ntools_json\x18\x08 \x01(\x0c\x12\x1c\n\x14provider_config_json\x18\t \x01(\x0c\x12)\n\x05trace\x18\n \x01(\x0b\x32\x1a.corlinman.v1.TraceContext"\xa2\x01\n\tChatChunk\x12\x0f\n\x05token\x18\x01 \x01(\tH\x00\x12$\n\x05usage\x18\x02 \x01(\x0b\x32\x13.corlinman.v1.UsageH\x00\x12,\n\x06\x66inish\x18\x03 \x01(\x0e\x32\x1a.corlinman.v1.FinishReasonH\x00\x12(\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x17.corlinman.v1.ErrorInfoH\x00\x42\x06\n\x04kind"\x84\x01\n\x0f\x43ompleteRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nmax_tokens\x18\x04 \x01(\r\x12)\n\x05trace\x18\x05 \x01(\x0b\x32\x1a.corlinman.v1.TraceContext"p\n\x10\x43ompleteResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12"\n\x05usage\x18\x02 \x01(\x0b\x32\x13.corlinman.v1.Usage\x12*\n\x06\x66inish\x18\x03 \x01(\x0e\x32\x1a.corlinman.v1.FinishReason*\x94\x01\n\x0c\x46inishReason\x12\x1d\n\x19\x46INISH_REASON_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x46INISH_STOP\x10\x01\x12\x11\n\rFINISH_LENGTH\x10\x02\x12\x14\n\x10\x46INISH_TOOL_CALL\x10\x03\x12\x19\n\x15\x46INISH_CONTENT_FILTER\x10\x04\x12\x10\n\x0c\x46INISH_ERROR\x10\x05\x32\x98\x01\n\x0bLLMProvider\x12>\n\x04\x43hat\x12\x19.corlinman.v1.ChatRequest\x1a\x17.corlinman.v1.ChatChunk(\x01\x30\x01\x12I\n\x08\x43omplete\x12\x1d.corlinman.v1.CompleteRequest\x1a\x1e.corlinman.v1.CompleteResponseB\x02H\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "corlinman.v1.llm_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\001"
    _globals["_FINISHREASON"]._serialized_start = 733
    _globals["_FINISHREASON"]._serialized_end = 881
    _globals["_CHATREQUEST"]._serialized_start = 68
    _globals["_CHATREQUEST"]._serialized_end = 316
    _globals["_CHATCHUNK"]._serialized_start = 319
    _globals["_CHATCHUNK"]._serialized_end = 481
    _globals["_COMPLETEREQUEST"]._serialized_start = 484
    _globals["_COMPLETEREQUEST"]._serialized_end = 616
    _globals["_COMPLETERESPONSE"]._serialized_start = 618
    _globals["_COMPLETERESPONSE"]._serialized_end = 730
    _globals["_LLMPROVIDER"]._serialized_start = 884
    _globals["_LLMPROVIDER"]._serialized_end = 1036
# @@protoc_insertion_point(module_scope)
