# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corlinman/v1/plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "corlinman/v1/plugin.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from corlinman_grpc._generated.corlinman.v1 import (
    common_pb2 as corlinman_dot_v1_dot_common__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x63orlinman/v1/plugin.proto\x12\x0c\x63orlinman.v1\x1a\x19\x63orlinman/v1/common.proto"\xe0\x01\n\x0ePluginToolCall\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0e\n\x06plugin\x18\x02 \x01(\t\x12\x0c\n\x04tool\x18\x03 \x01(\t\x12\x11\n\targs_json\x18\x04 \x01(\x0c\x12-\n\x07\x62inding\x18\x05 \x01(\x0b\x32\x1c.corlinman.v1.ChannelBinding\x12\x13\n\x0bsession_key\x18\x06 \x01(\t\x12\x1d\n\x15\x61pproval_preconsented\x18\x07 \x01(\x08\x12)\n\x05trace\x18\x08 \x01(\x0b\x32\x1a.corlinman.v1.TraceContext"\xde\x01\n\tToolEvent\x12*\n\x08progress\x18\x01 \x01(\x0b\x32\x16.corlinman.v1.ProgressH\x00\x12\x30\n\x06result\x18\x02 \x01(\x0b\x32\x1e.corlinman.v1.PluginToolResultH\x00\x12(\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x17.corlinman.v1.ErrorInfoH\x00\x12\x41\n\x11\x61waiting_approval\x18\x04 \x01(\x0b\x32$.corlinman.v1.PluginAwaitingApprovalH\x00\x42\x06\n\x04kind"-\n\x08Progress\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08\x66raction\x18\x02 \x01(\x02"M\n\x10PluginToolResult\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x13\n\x0bresult_json\x18\x02 \x01(\x0c\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x04"\x87\x01\n\x16PluginAwaitingApproval\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0e\n\x06plugin\x18\x02 \x01(\t\x12\x0c\n\x04tool\x18\x03 \x01(\t\x12\x19\n\x11\x61rgs_preview_json\x18\x04 \x01(\x0c\x12\x13\n\x0bsession_key\x18\x05 \x01(\t\x12\x0e\n\x06reason\x18\x06 \x01(\t2R\n\x0cPluginBridge\x12\x42\n\x07\x45xecute\x12\x1c.corlinman.v1.PluginToolCall\x1a\x17.corlinman.v1.ToolEvent0\x01\x42\x02H\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "corlinman.v1.plugin_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\001"
    _globals["_PLUGINTOOLCALL"]._serialized_start = 71
    _globals["_PLUGINTOOLCALL"]._serialized_end = 295
    _globals["_TOOLEVENT"]._serialized_start = 298
    _globals["_TOOLEVENT"]._serialized_end = 520
    _globals["_PROGRESS"]._serialized_start = 522
    _globals["_PROGRESS"]._serialized_end = 567
    _globals["_PLUGINTOOLRESULT"]._serialized_start = 569
    _globals["_PLUGINTOOLRESULT"]._serialized_end = 646
    _globals["_PLUGINAWAITINGAPPROVAL"]._serialized_start = 649
    _globals["_PLUGINAWAITINGAPPROVAL"]._serialized_end = 784
    _globals["_PLUGINBRIDGE"]._serialized_start = 786
    _globals["_PLUGINBRIDGE"]._serialized_end = 868
# @@protoc_insertion_point(module_scope)
