# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: corlinman/v1/vector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "corlinman/v1/vector.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from corlinman_grpc._generated.corlinman.v1 import (
    common_pb2 as corlinman_dot_v1_dot_common__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x63orlinman/v1/vector.proto\x12\x0c\x63orlinman.v1\x1a\x19\x63orlinman/v1/common.proto"\xd8\x01\n\x08RagQuery\x12\x14\n\x0cquery_vector\x18\x01 \x01(\x0c\x12\r\n\x05top_k\x18\x02 \x01(\r\x12\x11\n\toverfetch\x18\x03 \x01(\r\x12\r\n\x05scope\x18\x04 \x01(\t\x12\x13\n\x0bsession_key\x18\x05 \x01(\t\x12\x15\n\rrequired_tags\x18\x06 \x03(\t\x12\x15\n\rexcluded_tags\x18\x07 \x03(\t\x12\x17\n\x0frag_params_json\x18\x08 \x01(\x0c\x12)\n\x05trace\x18\t \x01(\x0b\x32\x1a.corlinman.v1.TraceContext"n\n\x07RagHits\x12"\n\x04hits\x18\x01 \x03(\x0b\x32\x14.corlinman.v1.RagHit\x12&\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x17.corlinman.v1.ErrorInfo\x12\x17\n\x0f\x63\x61ndidate_count\x18\x03 \x01(\r"\x93\x01\n\x06RagHit\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\x14\n\x0coffset_start\x18\x06 \x01(\x03\x12\x12\n\noffset_end\x18\x07 \x01(\x03\x12\x11\n\tmeta_json\x18\x08 \x01(\x0c"\xbe\x01\n\x05\x43hunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\tembedding\x18\x03 \x01(\x0c\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\x14\n\x0coffset_start\x18\x06 \x01(\x03\x12\x12\n\noffset_end\x18\x07 \x01(\x03\x12\r\n\x05scope\x18\x08 \x01(\t\x12\x17\n\x0flast_touched_at\x18\t \x01(\x03\x12\x11\n\tmeta_json\x18\n \x01(\x0c"\x7f\n\tUpsertAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x04\x12\x10\n\x08replaced\x18\x02 \x01(\x04\x12\x10\n\x08rejected\x18\x03 \x01(\x04\x12\x14\n\x0crejected_ids\x18\x04 \x03(\t\x12&\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x17.corlinman.v1.ErrorInfo2z\n\x06Vector\x12\x36\n\x05Query\x12\x16.corlinman.v1.RagQuery\x1a\x15.corlinman.v1.RagHits\x12\x38\n\x06Upsert\x12\x13.corlinman.v1.Chunk\x1a\x17.corlinman.v1.UpsertAck(\x01\x42\x02H\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "corlinman.v1.vector_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\001"
    _globals["_RAGQUERY"]._serialized_start = 71
    _globals["_RAGQUERY"]._serialized_end = 287
    _globals["_RAGHITS"]._serialized_start = 289
    _globals["_RAGHITS"]._serialized_end = 399
    _globals["_RAGHIT"]._serialized_start = 402
    _globals["_RAGHIT"]._serialized_end = 549
    _globals["_CHUNK"]._serialized_start = 552
    _globals["_CHUNK"]._serialized_end = 742
    _globals["_UPSERTACK"]._serialized_start = 744
    _globals["_UPSERTACK"]._serialized_end = 871
    _globals["_VECTOR"]._serialized_start = 873
    _globals["_VECTOR"]._serialized_end = 995
# @@protoc_insertion_point(module_scope)
