# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from corlinman_grpc._generated.corlinman.v1 import (
    vector_pb2 as corlinman_dot_v1_dot_vector__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in corlinman/v1/vector_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class VectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
            "/corlinman.v1.Vector/Query",
            request_serializer=corlinman_dot_v1_dot_vector__pb2.RagQuery.SerializeToString,
            response_deserializer=corlinman_dot_v1_dot_vector__pb2.RagHits.FromString,
            _registered_method=True,
        )
        self.Upsert = channel.stream_unary(
            "/corlinman.v1.Vector/Upsert",
            request_serializer=corlinman_dot_v1_dot_vector__pb2.Chunk.SerializeToString,
            response_deserializer=corlinman_dot_v1_dot_vector__pb2.UpsertAck.FromString,
            _registered_method=True,
        )


class VectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Upsert(self, request_iterator, context):
        """Upsert: client-streamed chunk ingest; server acks batch by batch."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Query": grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=corlinman_dot_v1_dot_vector__pb2.RagQuery.FromString,
            response_serializer=corlinman_dot_v1_dot_vector__pb2.RagHits.SerializeToString,
        ),
        "Upsert": grpc.stream_unary_rpc_method_handler(
            servicer.Upsert,
            request_deserializer=corlinman_dot_v1_dot_vector__pb2.Chunk.FromString,
            response_serializer=corlinman_dot_v1_dot_vector__pb2.UpsertAck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "corlinman.v1.Vector", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("corlinman.v1.Vector", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Vector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/corlinman.v1.Vector/Query",
            corlinman_dot_v1_dot_vector__pb2.RagQuery.SerializeToString,
            corlinman_dot_v1_dot_vector__pb2.RagHits.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Upsert(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/corlinman.v1.Vector/Upsert",
            corlinman_dot_v1_dot_vector__pb2.Chunk.SerializeToString,
            corlinman_dot_v1_dot_vector__pb2.UpsertAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
