"""corlinman-server — gRPC entrypoint for the Python AI plane."""

from __future__ import annotations

from corlinman_server.gateway_api import (
    Attachment,
    AttachmentKind,
    ChannelBinding,
    ChatEventStream,
    ChatService,
    ChatServiceBase,
    DoneEvent,
    ErrorEvent,
    InternalChatError,
    InternalChatEvent,
    InternalChatRequest,
    Message,
    Role,
    SharedChatService,
    TokenDeltaEvent,
    ToolCallEvent,
    Usage,
    internal_chat_error_from_corlinman_error,
)
from corlinman_server.main import main
from corlinman_server.scheduler import (
    ActionSpec,
    CronParseError,
    JobAction,
    JobSpec,
    RunRecord,
    SCHEDULER_SCHEMA_SQL,
    Schedule,
    SchedulerConfig,
    SchedulerHandle,
    SchedulerJob,
    SchedulerStore,
    SchedulerStoreConnectError,
    SchedulerStoreError,
    SubprocessOutcome,
    SubprocessOutcomeKind,
    dispatch,
    next_after,
    parse as parse_cron,
    run_subprocess,
    spawn as spawn_scheduler,
)
from corlinman_server.tenancy import (
    DEFAULT_TENANT_ID,
    TENANT_SLUG_REGEX_STR,
    AdminDb,
    AdminDbConnectError,
    AdminDbError,
    AdminExistsError,
    AdminRow,
    ApiKeyRow,
    FederationPeer,
    MintedApiKey,
    SCHEMA_SQL,
    TenantExistsError,
    TenantId,
    TenantIdEmpty,
    TenantIdError,
    TenantIdInvalidShape,
    TenantPool,
    TenantPoolConnectError,
    TenantPoolCreateDirError,
    TenantPoolError,
    TenantRow,
    default_tenant,
    hash_api_key_token,
    tenant_db_path,
    tenant_root_dir,
)

__all__ = [
    "main",
    # gateway_api
    "Attachment",
    "AttachmentKind",
    "ChannelBinding",
    "ChatEventStream",
    "ChatService",
    "ChatServiceBase",
    "DoneEvent",
    "ErrorEvent",
    "InternalChatError",
    "InternalChatEvent",
    "InternalChatRequest",
    "Message",
    "Role",
    "SharedChatService",
    "TokenDeltaEvent",
    "ToolCallEvent",
    "Usage",
    "internal_chat_error_from_corlinman_error",
    # tenancy
    "DEFAULT_TENANT_ID",
    "TENANT_SLUG_REGEX_STR",
    "AdminDb",
    "AdminDbConnectError",
    "AdminDbError",
    "AdminExistsError",
    "AdminRow",
    "ApiKeyRow",
    "FederationPeer",
    "MintedApiKey",
    "SCHEMA_SQL",
    "TenantExistsError",
    "TenantId",
    "TenantIdEmpty",
    "TenantIdError",
    "TenantIdInvalidShape",
    "TenantPool",
    "TenantPoolConnectError",
    "TenantPoolCreateDirError",
    "TenantPoolError",
    "TenantRow",
    "default_tenant",
    "hash_api_key_token",
    "tenant_db_path",
    "tenant_root_dir",
    # scheduler
    "ActionSpec",
    "CronParseError",
    "JobAction",
    "JobSpec",
    "RunRecord",
    "SCHEDULER_SCHEMA_SQL",
    "Schedule",
    "SchedulerConfig",
    "SchedulerHandle",
    "SchedulerJob",
    "SchedulerStore",
    "SchedulerStoreConnectError",
    "SchedulerStoreError",
    "SubprocessOutcome",
    "SubprocessOutcomeKind",
    "dispatch",
    "next_after",
    "parse_cron",
    "run_subprocess",
    "spawn_scheduler",
]
