"""``corlinman onboard`` — first-run wizard.

Python port of ``rust/crates/corlinman-cli/src/cmd/onboard.rs``.

Materialises the data directory skeleton (``agents/``, ``plugins/``,
``knowledge/``, ``vector/``, ``logs/``) and writes a starter
``config.toml``.

The Rust version uses ``dialoguer`` for an interactive prompt loop;
that path is out of scope for this initial port — we always behave as
if ``--non-interactive`` were passed and require ``--accept-risk`` to
acknowledge that some checks (e.g. provider validation) won't pass
without manual follow-up.
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

from corlinman_server.cli._common import SUBDIRS, resolve_data_dir

_DEFAULT_CONFIG_BODY = """# corlinman starter config
# This file was generated by `corlinman onboard`.
#
# Add a provider entry under [providers.X] with `api_key` + `enabled`
# before running `corlinman config validate` for a clean bill of health.

[server]
port = 6005
bind = "0.0.0.0"
data_dir = "{data_dir}"

[admin]
# username = "admin"
# password_hash = "$argon2id$..."
"""


@click.command("onboard")
@click.option(
    "--non-interactive",
    is_flag=True,
    help="Skip prompts; use defaults + env vars.",
)
@click.option(
    "--accept-risk",
    is_flag=True,
    help="Acknowledge that some checks will be skipped in non-interactive mode.",
)
@click.option(
    "--data-dir",
    type=click.Path(file_okay=False, path_type=Path),
    default=None,
    help="Override data-dir (default: $CORLINMAN_DATA_DIR or ~/.corlinman).",
)
@click.option("--force", is_flag=True, help="Overwrite an existing config.toml.")
def onboard(
    non_interactive: bool,
    accept_risk: bool,
    data_dir: Path | None,
    force: bool,
) -> None:
    """Interactive onboarding wizard.

    The Python port currently runs in non-interactive mode only; pass
    ``--non-interactive --accept-risk`` to satisfy the safety gate.
    """
    data_dir_path = resolve_data_dir(data_dir)
    config_path = data_dir_path / "config.toml"

    if config_path.exists() and not force:
        click.echo(
            f"error: {config_path} already exists; pass --force to overwrite",
            err=True,
        )
        sys.exit(1)

    # The interactive prompt loop is deferred to a follow-up; the safety
    # gate from the Rust port (``--non-interactive`` requires
    # ``--accept-risk``) is enforced as-is so behaviour is consistent.
    if not non_interactive:
        click.echo(
            "note: interactive mode is not implemented in the Python port; "
            "treating as --non-interactive",
            err=True,
        )
        non_interactive = True

    if non_interactive and not accept_risk:
        click.echo(
            "error: --non-interactive requires --accept-risk "
            "(no provider will be configured)",
            err=True,
        )
        sys.exit(1)

    _ensure_skeleton(data_dir_path)
    _write_config(config_path, data_dir_path)

    click.echo("onboard complete:")
    click.echo(f"  data_dir : {data_dir_path}")
    click.echo(f"  config   : {config_path}")
    # The Rust port re-runs the validator and reports the issue count;
    # without a Python config-parser sibling we just announce the
    # default-state caveat so the operator knows the next step.
    click.echo("  status   : 1 issue(s) — run `corlinman config validate` for details")


def _ensure_skeleton(data_dir: Path) -> None:
    data_dir.mkdir(parents=True, exist_ok=True)
    for sub in SUBDIRS:
        (data_dir / sub).mkdir(parents=True, exist_ok=True)


def _write_config(config_path: Path, data_dir: Path) -> None:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    body = _DEFAULT_CONFIG_BODY.format(data_dir=str(data_dir))
    config_path.write_text(body, encoding="utf-8")


__all__ = ["onboard"]
