"""``corlinman-mcp-server`` — Python port of the Rust ``corlinman-mcp``
crate.

Implements an MCP (Model Context Protocol, 2024-11-05) server over
WebSocket plus a matching stdio client peer. The public surface mirrors
the crate 1:1; the on-the-wire JSON shape is identical to the Rust
implementation so a single MCP client can be pointed at either.

Top-level re-exports:

* :class:`McpServer` / :class:`McpServerConfig` — WebSocket server
* :class:`AdapterDispatcher` / :class:`ServerInfo` — dispatcher
* :class:`ToolsAdapter` / :class:`ResourcesAdapter` /
  :class:`PromptsAdapter` — capability adapters
* :class:`SessionContext`, :class:`SessionState`, :class:`SessionPhase`
* :class:`TokenAcl`, :func:`resolve_token`, :data:`DEFAULT_TENANT_ID`
* :class:`McpError` (+ subclasses), :class:`JsonRpcError`,
  :class:`JsonRpcRequest`, :class:`JsonRpcResponse`
* :data:`MCP_PROTOCOL_VERSION`, :data:`JSONRPC_VERSION`
* :mod:`error_codes` numeric constants
* :class:`McpClient` — outbound stdio JSON-RPC peer
"""

from corlinman_mcp_server.adapters import (
    CapabilityAdapter,
    SessionContext,
    glob_match,
)
from corlinman_mcp_server.auth import (
    DEFAULT_TENANT_ID,
    TokenAcl,
    resolve_token,
)
from corlinman_mcp_server.bridges import (
    CancellationToken,
    MemoryDoc,
    MemoryHit,
    MemoryHost,
    MemoryQuery,
    NullPersonaProvider,
    PersonaSnapshotProvider,
    PluginCapabilities,
    PluginCommunication,
    PluginEntry,
    PluginEntryPoint,
    PluginInput,
    PluginManifest,
    PluginOutput,
    PluginOutputAcceptedForLater,
    PluginOutputError,
    PluginOutputSuccess,
    PluginRegistry,
    PluginRuntime,
    PluginTool,
    ProgressSink,
    SkillEntry,
    SkillRegistry,
)
from corlinman_mcp_server.client import (
    McpClient,
    McpClientDisconnected,
    McpClientError,
    McpClientMissingStdioError,
    McpClientServerError,
    McpClientSpawnError,
    McpClientWriteError,
)
from corlinman_mcp_server.dispatch import (
    AdapterDispatcher,
    FrameHandler,
    ServerInfo,
    StubMethodNotFoundHandler,
)
from corlinman_mcp_server.errors import (
    McpAuthError,
    McpError,
    McpInternalError,
    McpInvalidParamsError,
    McpInvalidRequestError,
    McpMethodNotFoundError,
    McpParseError,
    McpSessionNotInitializedError,
    McpToolNotAllowedError,
    McpTransportError,
)
from corlinman_mcp_server.prompts import PromptsAdapter
from corlinman_mcp_server.resources import ResourcesAdapter
from corlinman_mcp_server.session import (
    INITIALIZED_NOTIFICATION,
    INITIALIZE_METHOD,
    SessionPhase,
    SessionState,
    initialize_reply,
)
from corlinman_mcp_server.tools import (
    CollectingProgressBridge,
    NullProgressBridge,
    ProgressBridge,
    ProgressEvent,
    ToolsAdapter,
    decode_tool_name,
    encode_tool_name,
)
from corlinman_mcp_server.transport import (
    CLOSE_CODE_MESSAGE_TOO_BIG,
    DEFAULT_MAX_FRAME_BYTES,
    McpServer,
    McpServerConfig,
)
from corlinman_mcp_server.types import (
    JSONRPC_VERSION,
    MCP_PROTOCOL_VERSION,
    ClientCapabilities,
    Implementation,
    InitializeParams,
    InitializeResult,
    JsonRpcError,
    JsonRpcErrorResponse,
    JsonRpcRequest,
    JsonRpcResponse,
    JsonRpcResultResponse,
    JsonValue,
    Prompt,
    PromptArgument,
    PromptMessage,
    PromptRole,
    PromptsCapability,
    PromptsGetParams,
    PromptsGetResult,
    PromptsListResult,
    Resource,
    ResourcesCapability,
    ResourcesListParams,
    ResourcesListResult,
    ResourcesReadParams,
    ResourcesReadResult,
    ServerCapabilities,
    TextContent,
    TextResourceContent,
    ToolDescriptor,
    ToolsCallParams,
    ToolsCallResult,
    ToolsCapability,
    ToolsListResult,
    error_codes,
    prompt_text_content,
    text_content,
    text_resource,
)

__all__ = [
    "AdapterDispatcher",
    "CLOSE_CODE_MESSAGE_TOO_BIG",
    "CancellationToken",
    "CapabilityAdapter",
    "ClientCapabilities",
    "CollectingProgressBridge",
    "DEFAULT_MAX_FRAME_BYTES",
    "DEFAULT_TENANT_ID",
    "FrameHandler",
    "INITIALIZE_METHOD",
    "INITIALIZED_NOTIFICATION",
    "Implementation",
    "InitializeParams",
    "InitializeResult",
    "JSONRPC_VERSION",
    "JsonRpcError",
    "JsonRpcErrorResponse",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "JsonRpcResultResponse",
    "JsonValue",
    "MCP_PROTOCOL_VERSION",
    "McpAuthError",
    "McpClient",
    "McpClientDisconnected",
    "McpClientError",
    "McpClientMissingStdioError",
    "McpClientServerError",
    "McpClientSpawnError",
    "McpClientWriteError",
    "McpError",
    "McpInternalError",
    "McpInvalidParamsError",
    "McpInvalidRequestError",
    "McpMethodNotFoundError",
    "McpParseError",
    "McpServer",
    "McpServerConfig",
    "McpSessionNotInitializedError",
    "McpToolNotAllowedError",
    "McpTransportError",
    "MemoryDoc",
    "MemoryHit",
    "MemoryHost",
    "MemoryQuery",
    "NullPersonaProvider",
    "NullProgressBridge",
    "PersonaSnapshotProvider",
    "PluginCapabilities",
    "PluginCommunication",
    "PluginEntry",
    "PluginEntryPoint",
    "PluginInput",
    "PluginManifest",
    "PluginOutput",
    "PluginOutputAcceptedForLater",
    "PluginOutputError",
    "PluginOutputSuccess",
    "PluginRegistry",
    "PluginRuntime",
    "PluginTool",
    "ProgressBridge",
    "ProgressEvent",
    "ProgressSink",
    "Prompt",
    "PromptArgument",
    "PromptMessage",
    "PromptRole",
    "PromptsAdapter",
    "PromptsCapability",
    "PromptsGetParams",
    "PromptsGetResult",
    "PromptsListResult",
    "Resource",
    "ResourcesAdapter",
    "ResourcesCapability",
    "ResourcesListParams",
    "ResourcesListResult",
    "ResourcesReadParams",
    "ResourcesReadResult",
    "ServerCapabilities",
    "ServerInfo",
    "SessionContext",
    "SessionPhase",
    "SessionState",
    "SkillEntry",
    "SkillRegistry",
    "StubMethodNotFoundHandler",
    "TextContent",
    "TextResourceContent",
    "TokenAcl",
    "ToolDescriptor",
    "ToolsAdapter",
    "ToolsCallParams",
    "ToolsCallResult",
    "ToolsCapability",
    "ToolsListResult",
    "decode_tool_name",
    "encode_tool_name",
    "error_codes",
    "glob_match",
    "initialize_reply",
    "prompt_text_content",
    "resolve_token",
    "text_content",
    "text_resource",
]
